### ISSUE TITLE
Paparan Tarikh pada Dashboard

### ISSUE THREAD

**Issue by ladyzhacker** [mdridzuan80/kejora#13]
![dashboard](https://user-images.githubusercontent.com/27323584/29608509-efc049b4-8826-11e7-9fc3-2680c3fd37e7.jpg)
tarikh yang dipaparkan sehingga 18hb Ogos sahaja

**Comment by mdridzuan80** [comment]
Ini bukan error.. tetapi list kehadiran yang bermasalah seperti lewat, tak punch dan balik awal.
