### ISSUE TITLE
Maklumat PPP

### ISSUE THREAD

**Issue by ladyzhacker** [mdridzuan80/kejora#8]
Dalam maklumat kakitangan, Nama PPP betul tetapi no kad pengenalan bukan kepunyaan PPP

**Comment by mdridzuan80** [comment]
Salam.. yang ni saya dah check.. x der masalah dengan paparan ni..
Ada contoh user yang masalah tak?

**Comment by mdridzuan80** [comment]
Bukan masalah.. tetapi kesilapan menetapkan PPP
